swagger: "2.0"
info:
  version: 1.0.0
  title: jaedye
  description: An API to interface with the Jaedye backend
  termsOfService: http://swagger.io/terms/
  contact:
    name: Yuan Yu Chuan
    email: yuchuan@u.nus.edu
    url: www.example.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: jaedye.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/facebook:
    get:
      description: Sends facebook authentication token in exchange for a user profile
      operationId: authFacebook
      parameters:
        - name: access_token
          in: query
          description: Facebook access token
          required: true
          type: string
      responses:
        200:
          description: User Profile response
          schema:
            $ref: '#/definitions/UserProfile'
        default:
          description: Unauthorized response
  /auth/google:
    get:
      description: Sends google authentication token in exchange for a user profile
      operationId: authGoogle
      parameters:
        - name: access_token
          in: query
          description: Google access token
          required: true
          type: string
      responses:
        200:
          description: User Profile response
          schema:
            $ref: '#/definitions/UserProfile'
        default:
          description: Unauthorized response
  /leaderboard:
    get:
      description: |
        Returns the leaderboard for the current user
      operationId: getLeaderboard
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: Attempt response
          schema:
            type: array
            items:
              $ref: '#/definitions/Attempt'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /friends:
    get:
      description: |
        Returns the current user's list of friends
      operationId: getFriends
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: Friends response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Add a new user as friend
      operationId: addFriend
      parameters:
        - name: Friend
          in: body
          description: User ID of Friend to add
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Friend Added
          schema:
            type: integer
            # $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the Attempt
      operationId: find Attempt by id
      parameters:
        - name: id
          in: path
          description: ID of Attempt to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Attempt response
          schema:
            $ref: '#/definitions/Attempt'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single Attempt based on the ID supplied
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of Attempt to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: Attempt deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  UserProfile:
    allOf:
      - $ref: '#/definitions/User'
      - required:
        - provider
        - providerId
        - providerToken
        properties:
          provider:
            type: string
          providerId:
            type: string
          providerToken:
            type: string
  User:
    required:
      - name
      - email
      - id
    properties:
      name:
        type: string
      email:
        type: string
        format: email
      id:
        type: integer
  Attempt:
    allOf:
      - $ref: '#/definitions/NewAttempt'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewAttempt:
    required:
      - startTime
      - targetTime
      - actualTime
    properties:
      startTime:
        type: string
        format: datetime
      targetTime:
        type: integer
        description: Target time (in seconds)
      actualTime:
        type: integer
        description: Actual time spent focused (in seconds)
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string